config/routes.rb
Rails.application.routes.draw do
  get 'home/index'

  resources :citations

  root 'home#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/citation.rb
class Citation < ApplicationRecord
  validates :citation, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/citations_controller.rb
class CitationsController < ApplicationController
  def new
    @citation = Citation.new
  end

  def create
    @citation = Citation.new(citation_params)

    if(@citation.author.empty?)
      @citation.author = "Unknown"
    end

    if @citation.save
      redirect_to :action => "index", :controller => "home"
    else
      render 'new'
    end
  end

  private
  def citation_params
    params.require(:citation).permit(:citation, :author)
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @citations = Citation.all
  end
end

app/views/citations/new.html.erb
<h2>New Citation</h2>

<%= form_with scope: :citation, url: citations_path, local: true do |form| %>

  <p>
    <%= form.label :citation %><br>
    <%= form.text_area :citation %>
  </p>

  <% if @citation.errors.any? %>
    <div id="error_explanation">
      <ul>
        <% @citation.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <p>
    <%= form.label :author %><br>
    <%= form.text_field :author %>
  </p>

  <p>
    <%= form.submit %>
  </p>
<% end %>

<%= link_to "<button>Home</button>".html_safe, home_index_path %>

app/views/home/index.html.erb
<h2>Hello, Netguru!</h2>
<h3>Listing of citations</h3>

<%= link_to "<button>Add new citation</button>".html_safe, new_citation_path %>

<% @citations.each do |citation| %>
  <section class="citation_section">
    <p class="citation_text">"<%= citation.citation %>"</p>
    <h5><%= citation.author %></h5>
  </section>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>App</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="grid-container">
      <div></div>
      <div><%= yield %></div>
      <div></div>
    </div>
  </body>
</html>